# Generated by Django 5.0.1 on 2024-02-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(max_length=4),
        ),
    ]
