# Generated by Django 4.2.1 on 2024-02-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0004_book_slug_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
