# Generated by Django 5.0.1 on 2024-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0011_book_hodnoceni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='hodnoceni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
