# Generated by Django 5.0.1 on 2024-03-05 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0013_alter_book_hodnoceni'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='epub_files/', validators=[django.core.validators.FileExtensionValidator(['epub'])]),
        ),
    ]
