# Generated by Django 5.0.1 on 2024-05-09 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihy', '0015_publisher_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, error_messages='Pouze formát EPUB nebo PDF.', null=True, upload_to='epub_files/', validators=[django.core.validators.FileExtensionValidator(['epub', 'pdf'])]),
        ),
    ]
